### ISSUE TITLE
Applications fullscreen to wrong monitor when window maximized through tiling

### ISSUE THREAD

**Issue by isRedacted** [linuxmint/muffin#656]
* Cinnamon version 5.4.12
 * Distribution - Mint 21
 * RTX 3060, NVIDIA driver version 520 but issue persists on 515 too
 * 64 bit

### Issue
When maximizing an application by dragging window to top edge of monitor and with relevant option enabled in settings, if the application is then made fullscreen it will work once and any subsequent fullscreens move to wrong monitor

### Steps to reproduce
1. Set "Maximize, instead of tile, when dragging a window to the top edge" setting on in Window Tiling
2. Open application (Brave browser, VLC, etc)
3. Drag to top
4. Make fullscreen, un-fullscreen, and fullscreen again

### Expected behaviour
Program fullscreens to monitor it is maximized to every time

### Other information
Universal to all applications that can be maximized in this way, issue only present on NVIDIA drivers (tested on xserver version 1:1.0.17-2 and works correctly)

**Comment by pilot51** [comment]
This used to not be a problem for me and it started happening after upgrading to Mint 21. I watch a lot of YouTube and that's where I experience it most if not all of the time. I usually have Firefox maximized on my right/secondary monitor and the video goes fullscreen to my left/primary monitor. I work around it by unmaximizing and maximizing the window and then it will fullscreen on the right monitor.

**Comment by VividLemon** [comment]
It would be nice if this issue got some more attention. It is quite annoying of an issue, that occurs, to the very least, once every time I use my machine

**Comment by mistrjirka** [comment]
I also get this issue.

**Comment by lizardlab** [comment]
I have similarly gotten this issue on my multi-monitor setup with **Firefox** specifically on any website that full screens, could be Youtube, Tubi, Vimeo etc.

**Comment by AndrewRutherfoord** [comment]
I'm having this issue in Chrome and noticed it mainly in YouTube when full screening a video, but the same thing happens when I click F11 on a chrome window. I have to do the same thing as @pilot51 to get it to maximize on my second monitor.

**Comment by ScottDemarest** [comment]
I'm getting this issue with fullscreening with okular pdf reader. Also a similar issue with gaomon drawing tablet driver not being able to select particular screens. A fix would be nice

**Comment by AndreiTS** [comment]
Having this issue on firefox, going fullscreen on any site. I have to restart cinammon to work again.

**Comment by ColdSpirit0** [comment]
Same for me. Happens when I move app from one screen to top of another screen in one action. After that, second and further fullscreen transition happens on the wrong screen. Reproducible in Chromium, Firefox, on Youtube and other sites, even with F11 key.

**Steps to reproduce**
1. Go to System settings -> Window Tiling
2. Check Maximize instead of tile option is enabled
3. Open Firefox
4. Move window to the first screen
5. Move window to top of the second screen
6. Press F11 twice: fullscreen happens in the second screen
7. Press F11 twice: fullscreen happens in the first screen
8. Press F11 twice: fullscreen happens in the first screen

You can do it vice versa - from second screen to first, same result.

Example:

https://github.com/linuxmint/muffin/assets/16982207/ac74c436-db33-4114-a2c7-536367441d44

**Comment by cursedastronaut** [comment]
I also do.

**Comment by FredNass** [comment]
This bug has been here for a couple of years and still annoys every user using Cinnamon desktop with multiple monitors every day, whatever the linux flavor they use. 

Can we **please** have this one investigated?

**Comment by AugieDog08** [comment]
Yeah, this is one of the only things that has annoyed me since switching to Mint from Windows.

**Comment by SirGamsay** [comment]
How can this still be an Issue, when it's been known since Mint 13 as discussed above, please fix. 
I the same Issue with my Browsers and Youtube. 
Mint seems to struggle with Fullscreen in general, when I try playing some Games that Launch in Fullscreen those also often Launch on the Wrong Monitor. Have to fix this with windowed mode.
Interesting thing is, that when I then click outside the Fullscreened Game the Game swings back to the Original Location on the wrong Monitor

**Comment by IrishBruse** [comment]
Still an issue on linux mint 22 with chrome and vlc

**Comment by ElryGH** [comment]
Yeah im regretting choosing mint

**Comment by jollycar** [comment]
Here in 2025, still an issue for Cinnamon 6.4.2

**Comment by SirGamsay** [comment]
Interestingly enough this Issue doesn't happen that often for me anymore. But another funny thing happens. I use Brave as a Browser and often when it opens maximized, there is a small bar on Top where I can still see my Desktop. Only some 1-2mm thick, but it's there. Wondering if anyone has similar behavior?

**Comment by FredNass** [comment]
That's probably due to multiples screens of different heights being aligned on bottom instead of top in screen adjustment preferences.

**Comment by IrishBruse** [comment]
@FredNass 
![image](https://github.com/user-attachments/assets/4abca57e-4aec-4132-969b-0455f6e3288e)
They are the same resolution but ones a 24" vs 22" i still get this issue

**Comment by SirGamsay** [comment]
> That's probably due to multiples screens of different heights being aligned on bottom instead of top in screen adjustment preferences.

I have two 27'' Monitors running 1920x1080. Both connected with Display Port. Only difference is 60Hz and 144Hz

**Comment by ggrrll** [comment]
still same issue here,  few specs 👇 

```
System:
  Kernel: 5.15.0-130-generic x86_64 bits: 64 compiler: gcc v: 11.4.0 Desktop: Cinnamon 6.0.4
    tk: GTK 3.24.33 wm: muffin vt: 7 dm: LightDM 1.30.0 Distro: Linux Mint 21.3 Virginia
    base: Ubuntu 22.04 jammy
Machine:
  Type: Laptop System: Dell product: XPS 13 7390 v: N/A serial: <superuser required> Chassis:
    type: 10 serial: <superuser required>
  Mobo: Dell model: 0G2D0W v: A00 serial: <superuser required> UEFI: Dell v: 1.11.0
    date: 09/28/2021
Graphics:
  Device-1: Intel CometLake-U GT2 [UHD Graphics] vendor: Dell driver: i915 v: kernel ports:
    active: DP-1,eDP-1 empty: DP-2,DP-3 bus-ID: 00:02.0 chip-ID: 8086:9b41 class-ID: 0300
  Device-2: Microdia Integrated_Webcam_HD type: USB driver: uvcvideo bus-ID: 1-5:2
    chip-ID: 0c45:6723 class-ID: 0e02
  Display: x11 server: X.Org v: 1.21.1.4 driver: X: loaded: modesetting unloaded: fbdev,vesa
    gpu: i915 display-ID: :0 screens: 1
  Screen-1: 0 s-res: 1920x2160 s-dpi: 96 s-size: 508x572mm (20.0x22.5") s-diag: 765mm (30.1")
  Monitor-1: DP-1 pos: primary,bottom model: LG (GoldStar) ULTRAGEAR serial: <filter>
    res: 1920x1080 hz: 144 dpi: 81 size: 600x340mm (23.6x13.4") diag: 690mm (27.2") modes:
    max: 1920x1080 min: 640x480
  Monitor-2: eDP-1 pos: primary,top model: AU Optronics res: 1920x1080 hz: 60 dpi: 166
    size: 293x162mm (11.5x6.4") diag: 335mm (13.2") modes: 1920x1080
  OpenGL: renderer: Mesa Intel UHD Graphics (CML GT2) v: 4.6 Mesa 23.2.1-1ubuntu3.1~22.04.3
    direct render: Yes
```
